apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ranchersupport.fullname" . }}
{{- if .Values.annotations }}
  annotations:
{{ toYaml .Values.annotations | indent 4 }}
{{- end }}
  labels:
    app: {{ template "ranchersupport.name" . }}
    chart: {{ template "ranchersupport.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    kubernetes.io/cluster-service: "true"
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ template "ranchersupport.name" . }}
      release: {{ .Release.Name }}
      kubernetes.io/cluster-service: "true"
  template:
    metadata:
    {{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
    {{- end }}
      labels:
        app: {{ template "ranchersupport.name" . }}
        release: {{ .Release.Name }}
        kubernetes.io/cluster-service: "true"
    spec:
      {{- if .Values.securityContext }}
      securityContext:
{{ toYaml .Values.securityContext | indent 8 }}
      {{- end }}
      serviceAccountName: {{ template "ranchersupport.serviceAccountName" . }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.manager_image.repository }}:{{ .Values.manager_image.tag }}"
        imagePullPolicy: {{ .Values.manager_image.pullPolicy }}
