{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "ranchersupport.name" . }}
    chart: {{ template "ranchersupport.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "ranchersupport.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
